import { mkdir, readFile, writeFile } from "node:fs/promises";

const packageJson = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
const version = packageJson.version;

if (!/^\d+\.\d+(?:\.\d+)?(?:[-+][0-9A-Za-z.-]+)?$/.test(version)) {
  throw new Error(`Version package.json invalide: ${version}`);
}

await mkdir(new URL("../src", import.meta.url), { recursive: true });

await writeFile(
  new URL("../src/appVersion.ts", import.meta.url),
  `// Generated by scripts/sync-version.mjs from package.json.\nexport const APP_VERSION = ${JSON.stringify(version)};\nexport const APP_VERSION_LABEL = \`v\${APP_VERSION}\`;\n`,
);


console.log(`Taf Sniffer version synced: v${version}`);
